### ISSUE TITLE
Standard Weight equation for Redbreast Sunfish and Spotted Sunfish

### ISSUE THREAD

**Issue by jcdoll79** [fishR-Core-Team/FSA#100]
Add new standard weight equations for Redbreast Sunfish _Leopis auritus_ and Spotted Sunfish _Lepomis punctatus_ from Bonvechio et al. (in press).
https://doi.org/10.1002/nafm.10869

**Comment by droglenc** [comment]
Jason ... I can not access the article anymore. If you can, can you send it to my gmail and I will do the update. Thanks.

**Comment by droglenc** [comment]
The authors provide Ws equations from using the RLP, EmP (linear), and EmP (quadratic) methods. They only recommended using the EmP (linear) method. In the past, I have only only include the *author-recommended* equation into `WSlit`. Assuming that we still want to do this then the equations to add are:

* **Redbreast Sunfish**
    * Metric: slope=3.1218, intercept=-5.0018, min.len=80mm, max.len=300mm
    * English: slope=3.1215 , intercept=-3.2727, min.len=3in, max.len=11.75in 
* **Spotted Sunfish**
    * Metric: slope=3.3343, intercept=-5.3739, min.len=70mm, max.len=200mm
    * English: slope=3.3343 , intercept=-3.3468, min.len=2.75in, max.len=8in 

No lengths for given for English units so I converted from the metric lengths and rounded to what seemed like common units (whole, half, or quarter inches) as I have done for other species and as noted in the documentation for `WSlit`.

----

While we are at it we should add their length categories to `PSDlit`. The values to add are

* **Redbreast Sunfish**
    * Metric: stock.cm=8, quality.cm=13, preferred.cm=18, memorable.cm=20, trophy.cm=25 
    * English: stock.in= , quality.in=3, preferred.in=5, memorable.in=7, trophy.in=8  
* **Spotted Sunfish**
    * Metric: stock.cm=5, quality.cm=10, preferred.cm=13, memorable.cm=15, trophy.cm=18
    * English: stock.in=2, quality.in=4, preferred.in=5, memorable.in=6, trophy.in=7

Note that the authors **DID** provide English values for the length categories.

----

Finally, the process by which I update this information is a bit convoluted. I will document here for the future (or in case we want to streamline this).

1. Enter new values into `WSlit.csv` in the `data-raw` folder of the package.
2. Open script in `aaaConvertCSV2RDATA.R` in the `data-raw` folder of the package.
3. Run line 9 to get a list of all of the CSV files
4. Uncomment and run line 11 with the number of the file that corresponds to `WSlit`
5. Run rest of the lines
6. Check to make sure that the data on `WSlit.rdata` in the `data` folder has been updated
7. Compile the package
8. Test to see if `WSval()` returns the intended values

Repeat this for `PSDlit` if that was changed.
