### ISSUE TITLE
Estimate Growth Parameters Length Frequency Data 

### ISSUE THREAD

**Issue by MLV99** [fishR-Core-Team/FSA#105]
I have length frequency data (no age data) and I need to extract the growth parameters of VBGF to eventually create a length converted catch curve. 

I have read the literature and the available functions in the TropFishR and FSA package yet I still cannot make it work for my data and I am also new to R studio. 

Example of data:
df 

length | freq
210  | 2
220 | 7
230 | 3
240 | 13
250 | 33

What function should be applied? 

Any help is appreciated

**Comment by jcdoll79** [comment]
Hi,
Unfortunately, the growth models in FSA require length and age. I would suggest checking out the TropFishR package which has numerous functions for analyzing length frequency data. 
https://github.com/tokami/TropFishR
Jason
