### ISSUE TITLE
Unclear reference to t*

### ISSUE THREAD

**Issue by arni-magnusson** [fishR-Core-Team/FSA#113]
Hi. Related to #112, I noticed in the ?growthModels help page an unclear reference to t*:

> * Gompertz
>   * Within FSA, L0 is the mean length at age 0, Linf is the mean asymptotic length, ti is the age at the inflection point, gi is the instantaneous growth rate at the inflection point, t* is a dimensionless parameter related to time/age, and a is a dimensionless parameter related to growth. 

This is in the section documenting the Gompertz growth function. While reading, I was curious what this t* parameter was referring to. Of the many parameterizations of the Gompertz function, it's not clear which function argument corresponds to the t* in help page. Each parameterization has four arguments:

```
Ricker1     t  Linf  gi  ti
Ricker2     t        gi      L0  a
Ricker3     t  Linf  gi          a
QD1         t        gi      L0  a
QD2         t  Linf  gi          a
QD3         t  Linf  gi             t0
Original    t  Linf  gi          a
Troynikov1     Linf  gi                 Lm  dt
Troynikov2     Linf  gi                 Lm  dt
```

Is it possible that the t* in the help page is referring to the QD3 argument t0?

**Comment by droglenc** [comment]
Yes, t* is a typo that should be t0.

Most likely this is a holdover that I missed from trying to sort out and systemetize the parameters in the various Gompertz parameterizations.

Thanks for pointing this out. I will make the correction for the next version of `FSA`.

**Comment by droglenc** [comment]
Now corrected in the dev branch.
