### ISSUE TITLE
Why are the survival rates >1 when using mrOpen in the package FSA?

### ISSUE THREAD

**Issue by qoswald** [fishR-Core-Team/FSA#92]
I am currently doing some population analyses with the package "FSA" in R. By using the mrOpencommand, I want to get the survival rate. My rawdata is a simple table with one row per indidivual, one column per sample date and values of 0 and 1 (for not capured or captured during that respective sampling).

id 	total.captures 	date1 	date2 	date3 	etc
1 	3 	1 	1 	1 	...
2 	1 	1 	0 	0 	...

This is the exact code:

hold.data<-capHistSum(data, cols2use = c(3:13))
est.data<-mrOpen(hold.data)
summary(est.data)
confint(est.data)

It seems to work out, as I get the tables and summaries with all the parameters. See this example:

![Screenshot 2022-04-14 115711](https://user-images.githubusercontent.com/57616136/163385142-91d6165f-2c93-4c04-95a5-9a09f430f44a.png)

However, there's a problem with the survival estimate phi.
The phi value is not between 0 and 1, but in some cases, exceeds 1.

Any idea, what went wrong here?

Thanks,
Pia

**Comment by jcdoll79** [comment]
Hi Pia,

When phi > 1, it typically indicates an over-parameterized model (i.e,, the data don't support the underlying model that is being estimated). Would you be willing to share a subset of your data that recreates the issue? You can also email me the data directly, if you would like, jason.doll@fmarion.edu.

Jason

**Comment by qoswald** [comment]
Thanks for your fast answers! 
@jcdoll79  I'll sent you a mail.

Pia

**Comment by jcdoll79** [comment]
Hi Pia,
Thanks for sending me your data to investigate the issue. @droglenc suspicions are correct, there are too few recaptured fish to get good estimates of survival or abundance. The only suggestion I have is to try a Bayesian approach towards fitting the open Jolly-Seber model where you can specify prior information to provide more realistic estimates (this would require coding the model yourself). You might also try an individual Cormack-Jolly-Seber model. The CJS model will estimate survival but it doesn't directly estimate population size. As of now, FSA does not support CJS models.
Jason

**Comment by qoswald** [comment]
Hi Jason,

 

thank you so much, again, for helping me with this issue.

It seems I need to dive deeper into Bayesian approaches.

Just to make sure, did I understand you correctly that with my data also the estimated population size is not valid?

Or was this for the survival estimates only?

 

Have a nice Easter!

Best wishes,

Pia

 

 

Von: Jason Doll ***@***.***> 
Gesendet: Donnerstag, 14. April 2022 21:25
An: fishR-Core-Team/FSA ***@***.***>
Cc: Pia Oswald ***@***.***>; Author ***@***.***>
Betreff: Re: [fishR-Core-Team/FSA] Why are the survival rates >1 when using mrOpen in the package FSA? (Issue #92)

 

Hi Pia,
Thanks for sending me your data to investigate the issue. @droglenc <https://github.com/droglenc>  suspicions are correct, there are too few recaptured fish to get good estimates of survival or abundance. The only suggestion I have is to try a Bayesian approach towards fitting the open Jolly-Seber model where you can specify prior information to provide more realistic estimates (this would require coding the model yourself). You might also try an individual Cormack-Jolly-Seber model. The CJS model will estimate survival but it doesn't directly estimate population size. As of now, FSA does not support CJS models.
Jason

**Comment by jcdoll79** [comment]
Hi Pia,
That is correct. The population estimates and the survival estimates are not valid and should not be interpreted.
Jason

**Comment by qoswald** [comment]
Hi Jason,

 

okay, I will try another approach.

Thanks for your help!

 

Best wishes,

Pia

 

 

Von: Jason Doll ***@***.***> 
Gesendet: Samstag, 16. April 2022 20:43
An: fishR-Core-Team/FSA ***@***.***>
Cc: Pia Oswald ***@***.***>; Author ***@***.***>
Betreff: Re: [fishR-Core-Team/FSA] Why are the survival rates >1 when using mrOpen in the package FSA? (Issue #92)

 

Hi Pia,
That is correct. The population estimates and the survival estimates are not valid and should not be interpreted.
Jason
